// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/search-properties.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.96.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-properties.ts
var search_properties_default = defineTool({
  name: "search_properties",
  title: "Buscar propiedades",
  description: "Busca propiedades del cat\xE1logo interno por texto (t\xEDtulo, c\xF3digo PLT, direcci\xF3n), estado, tipo, ciudad o barrio.",
  inputSchema: {
    query: z.string().trim().min(1).optional().describe("Texto libre: t\xEDtulo, c\xF3digo PLT, direcci\xF3n o barrio."),
    status: z.string().trim().optional().describe("Estado comercial, ej: available, reserved, rented, sold."),
    property_type: z.string().trim().optional().describe("Tipo de propiedad, ej: departamento, casa, terreno."),
    city: z.string().trim().optional().describe("Ciudad."),
    limit: z.number().int().min(1).max(50).default(20).describe("M\xE1ximo de resultados (1-50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, status, property_type, city, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("No autenticado.");
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("properties").select(
      "id, property_code, title, property_type, status, city, neighborhood, address, bedrooms, bathrooms, area_m2, rental_price, sale_price, currency, is_published"
    ).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    if (property_type) q = q.eq("property_type", property_type);
    if (city) q = q.ilike("city", `%${city}%`);
    if (query) {
      const like = `%${query}%`;
      q = q.or(
        `title.ilike.${like},property_code.ilike.${like},address.ilike.${like},neighborhood.ilike.${like}`
      );
    }
    const { data, error } = await q;
    if (error) throw new ToolError(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, properties: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-property.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_property_default = defineTool2({
  name: "get_property",
  title: "Ficha de propiedad",
  description: "Devuelve la ficha completa de una propiedad por c\xF3digo PLT o por id.",
  inputSchema: {
    property_code: z2.string().trim().min(1).optional().describe("C\xF3digo PLT, ej: PLT-2026-0368."),
    property_id: z2.string().uuid().optional().describe("UUID de la propiedad.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ property_code, property_id }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("No autenticado.");
    if (!property_code && !property_id) throw new ToolError2("Indic\xE1 property_code o property_id.");
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("properties").select(
      "id, property_code, title, internal_title, description, property_type, status, address, city, neighborhood, unit_id, bedrooms, bathrooms, area_m2, has_garage, garage_number, rental_price, rental_period, sale_price, currency, management_fee_pct, captor_agent_id, owner_id, is_published, visible_en_portal, is_featured, disponible_desde, key_location, key_holder_name, amenities, created_at, updated_at"
    ).limit(1);
    q = property_id ? q.eq("id", property_id) : q.eq("property_code", property_code);
    const { data, error } = await q.maybeSingle();
    if (error) throw new ToolError2(error.message);
    if (!data) throw new ToolError2("Propiedad no encontrada (o sin permiso para verla).");
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { property: data }
    };
  }
});

// src/lib/mcp/tools/list-contracts.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_contracts_default = defineTool3({
  name: "list_contracts",
  title: "Listar contratos",
  description: "Lista contratos de alquiler/venta, con filtro por estado o por nombre de inquilino/propietario.",
  inputSchema: {
    status: z3.string().trim().optional().describe("Estado del contrato, ej: active, terminated, draft."),
    party: z3.string().trim().min(1).optional().describe("Texto a buscar en inquilino o propietario."),
    limit: z3.number().int().min(1).max(50).default(20).describe("M\xE1ximo de resultados (1-50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, party, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError3("No autenticado.");
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("contracts").select(
      "id, contract_type, status, tenant_name, landlord_name, property_address, monthly_rent, currency, start_date, end_date, periodicity, payment_day_from, payment_day_to, responsible_agent_id"
    ).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    if (party) {
      const like = `%${party}%`;
      q = q.or(`tenant_name.ilike.${like},landlord_name.ilike.${like},property_address.ilike.${like}`);
    }
    const { data, error } = await q;
    if (error) throw new ToolError3(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, contracts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-pending-receivables.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var list_pending_receivables_default = defineTool4({
  name: "list_pending_receivables",
  title: "Deudas pendientes (morosos)",
  description: "Lista cuotas/deudas pendientes o vencidas (alquiler, expensas, energ\xEDa, pagar\xE9s) con importe, vencimiento y deudor.",
  inputSchema: {
    debtor: z4.string().trim().min(1).optional().describe("Texto a buscar en el nombre del deudor."),
    concept: z4.string().trim().optional().describe("Concepto exacto, ej: alquiler, expensas, energia."),
    overdue_only: z4.boolean().default(false).describe("Solo las ya vencidas a la fecha de hoy."),
    limit: z4.number().int().min(1).max(100).default(30).describe("M\xE1ximo de resultados (1-100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ debtor, concept, overdue_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError4("No autenticado.");
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("receivables").select(
      "id, debtor_name, debtor_role, concept, description, amount, currency, due_date, status, unit_code, building_id, property_id, total_cobrado, paid_amount, notes"
    ).neq("status", "paid").order("due_date", { ascending: true }).limit(limit ?? 30);
    if (debtor) q = q.ilike("debtor_name", `%${debtor}%`);
    if (concept) q = q.eq("concept", concept);
    if (overdue_only) q = q.lt("due_date", (/* @__PURE__ */ new Date()).toISOString().slice(0, 10));
    const { data, error } = await q;
    if (error) throw new ToolError4(error.message);
    const total = (data ?? []).reduce((sum, r) => sum + Number(r.amount ?? 0), 0);
    return {
      content: [{ type: "text", text: JSON.stringify({ total_pendiente: total, items: data ?? [] }, null, 2) }],
      structuredContent: { count: data?.length ?? 0, total_pendiente: total, receivables: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-pipeline-deals.ts
import { defineTool as defineTool5, ToolError as ToolError5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var list_pipeline_deals_default = defineTool5({
  name: "list_pipeline_deals",
  title: "Oportunidades del pipeline",
  description: "Lista oportunidades del CRM (pipeline) visibles para el usuario, con etapa, cliente y pr\xF3xima acci\xF3n.",
  inputSchema: {
    stage: z5.string().trim().optional().describe("Etapa del pipeline a filtrar."),
    only_mine: z5.boolean().default(true).describe("Solo las oportunidades asignadas al usuario autenticado."),
    limit: z5.number().int().min(1).max(50).default(20).describe("M\xE1ximo de resultados (1-50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ stage, only_mine, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError5("No autenticado.");
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("pipeline_deals").select(
      "id, pipeline_type, stage, client_name, client_phone, property_title_snap, next_action_date, next_step, follow_up_date, estimated_commission, agent_id, notes, updated_at"
    ).order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (stage) q = q.eq("stage", stage);
    if (only_mine !== false) {
      const userId = ctx.getUserId();
      if (!userId) throw new ToolError5("No se pudo determinar el usuario autenticado.");
      q = q.eq("agent_id", userId);
    }
    const { data, error } = await q;
    if (error) throw new ToolError5(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, deals: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ccxjxpgeppxfcwlzmvbd";
var mcp_default = defineMcp({
  name: "plusterra-home-hub",
  title: "Plusterra Home Hub",
  version: "0.1.0",
  instructions: "Herramientas del sistema de gesti\xF3n inmobiliaria Plusterra. Us\xE1 search_properties y get_property para el cat\xE1logo interno, list_contracts para contratos, list_pending_receivables para morosos y deudas pendientes, y list_pipeline_deals para oportunidades del CRM. Todos los datos respetan los permisos del usuario conectado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_properties_default, get_property_default, list_contracts_default, list_pending_receivables_default, list_pipeline_deals_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
